SUPABASE_URL = "https://knimnpchbhtfwxhdptbi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuaW1ucGNoYmh0Znd4aGRwdGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMTY4MTUsImV4cCI6MjA5MTc5MjgxNX0.vxwzi5o_X41Fmkve5V8zgOBRLgPpQUHSED7qBrJz-cU"

[auth_users.atlas_admin]
password = "AtlasSecure2026!"
name = "Atlas Admin"
role = "Admin"

[auth_users.atlas_sales]
password = "SolarField2026!"
name = "Atlas Sales"
role = "Sales"